routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'PageController@about')->name('about');
Route::post('/about',  'PageController@about')->name('about');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => ['web']], function () {
        Route::get('business_partners/identity-document-autocomplete', 'Business_PartnersController@dataIdentityDocument')->name('business_partners.identity-document-autocomplete');
        Route::resource('business_partners', 'Business_PartnersController');

        Route::resource('business_partner_documents', 'Business_Partner_DocumentsController');
        Route::resource('material_providers', 'Material_ProvidersController');
        Route::resource('prices_list', 'Prices_ListController');        

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('stocks/list', 'StocksController@list')->name('stocks.list');
            Route::resource('stocks', 'StocksController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('material_measures/list', 'Material_MeasuresController@list')->name('material_measures.list');
            Route::resource('material_measures', 'Material_MeasuresController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('good_entry/list', 'Good_EntryController@list')->name('good_entry.list');
            Route::get('good_entry/add-provider', 'Good_EntryController@addProvider')->name('good_entry.addProvider');
            Route::get('good_entry/providers-autocomplete', 'Good_EntryController@dataProviders')->name('good_entry.providers-autocomplete');
            Route::get('good_entry/process', 'Good_EntryController@process')->name('good_entry.process');
            Route::resource('good_entry', 'Good_EntryController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('detail_good_entry/materials-autocomplete', 'Detail_Good_EntryController@dataMaterials')->name('detail_good_entry.materials-autocomplete');
            Route::resource('detail_good_entry', 'Detail_Good_EntryController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('delivery_order/list', 'Delivery_OrderController@list')->name('delivery_order.list');
            Route::get('delivery_order/add-customer', 'Delivery_OrderController@addCustomer')->name('delivery_order.addCustomer');
            Route::get('delivery_order/customers-autocomplete', 'Delivery_OrderController@dataCustomers')->name('delivery_order.customers-autocomplete');
            Route::get('delivery_order/process', 'Delivery_OrderController@process')->name('delivery_order.process');
            Route::resource('delivery_order', 'Delivery_OrderController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('detail_delivery_order/materials-autocomplete', 'Detail_Delivery_OrderController@dataMaterials')->name('detail_delivery_order.materials-autocomplete');
            Route::get('detail_delivery_order/material-measures-autocomplete', 'Detail_Delivery_OrderController@dataMeasures')->name('detail_delivery_order.material-measures-autocomplete');
            Route::resource('detail_delivery_order', 'Detail_Delivery_OrderController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('material/add-measure', 'MaterialController@addMeasure')->name('material.addMeasure');
            Route::resource('material', 'MaterialController');
        });

    });    

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/Material_Measure.php
<?php

namespace App;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;


class Material_Measure extends BaseModel
{
  //use Traits\HasCompositePrimaryKey;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'material_measures';

    /**
     * The primary key of the table.
     *
     * @var array
     */
    //protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['material_id', 'measure_id'];

    use SoftDeletes;
    protected $dates = ['deleted_at'];

    public function material() {
        return $this->belongsTo('App\Material');
    }

    public function measure() {
        return $this->belongsTo('App\Measure');
    }    
}

app/Http/Controllers/Admin/Material_MeasuresController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Admin\Voyager\VoyagerBaseController as BaseVoyagerController;
use TCG\Voyager\Facades\Voyager;

use App\Measure;
use App\Material;
use App\Material_Measure;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Session;

class Material_MeasuresController extends BaseVoyagerController
{

    public function index(Request $request)
    {
        // GET THE SLUG, ex. 'posts', 'pages', etc.
        $slug = $this->getSlug($request);

        // GET THE DataType based on the slug
        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Check permission
        $this->authorize('browse', app($dataType->model_name));

        $getter = $dataType->server_side ? 'paginate' : 'get';

        $search = (object) ['value' => $request->get('s'), 'key' => $request->get('key'), 'filter' => $request->get('filter')];
        $searchable = $dataType->server_side ? array_keys(SchemaManager::describeTable(app($dataType->model_name)->getTable())->toArray()) : '';
        $orderBy = $request->get('order_by');
        $sortOrder = $request->get('sort_order', null);

        // Next Get or Paginate the actual content from the MODEL that corresponds to the slug DataType
        if (strlen($dataType->model_name) != 0) {
            $relationships = $this->getRelationships($dataType);

            $model = app($dataType->model_name);
            $query = $model::select('*')->with($relationships);

            // If a column has a relationship associated with it, we do not want to show that field
            $this->removeRelationshipField($dataType, 'browse');

            if ($search->value && $search->key && $search->filter) {
                $search_filter = ($search->filter == 'equals') ? '=' : 'LIKE';
                $search_value = ($search->filter == 'equals') ? $search->value : '%'.$search->value.'%';
                $query->where($search->key, $search_filter, $search_value);
            }

            if ($orderBy && in_array($orderBy, $dataType->fields())) {
                $querySortOrder = (!empty($sortOrder)) ? $sortOrder : 'DESC';
                $dataTypeContent = call_user_func([
                    $query->orderBy($orderBy, $querySortOrder),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([$query->orderBy($model->getKeyName(), 'DESC'), $getter]);
            }

            // Replace relationships' keys for labels and create READ links if a slug is provided.
            $dataTypeContent = $this->resolveRelations($dataTypeContent, $dataType);
        } else {
            // If Model doesn't exist, get data from table name
            $dataTypeContent = call_user_func([DB::table($dataType->name), $getter]);
            $model = false;
        }

        // Check if BREAD is Translatable
        if (($isModelTranslatable = is_bread_translatable($model))) {
            $dataTypeContent->load('translations');
        }

        // Check if server side pagination is enabled
        $isServerSide = isset($dataType->server_side) && $dataType->server_side;

        $view = 'voyager::bread.browse';

        if (view()->exists("voyager::$slug.browse")) {
            $view = "voyager::$slug.browse";
        }

        return Voyager::view($view, compact(
            'dataType',
            'dataTypeContent',
            'isModelTranslatable',
            'search',
            'orderBy',
            'sortOrder',
            'searchable',
            'isServerSide'
        ));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Check permission
        $this->authorize('add', app($dataType->model_name));

        $dataTypeContent = (strlen($dataType->model_name) != 0)
                            ? new $dataType->model_name()
                            : false;

        foreach ($dataType->addRows as $key => $row) {
            $details = json_decode($row->details);
            $dataType->addRows[$key]['col_width'] = isset($details->width) ? $details->width : 100;
        }

        // If a column has a relationship associated with it, we do not want to show that field
        $this->removeRelationshipField($dataType, 'add');

        // Check if BREAD is Translatable
        $isModelTranslatable = is_bread_translatable($dataTypeContent);

        $view = 'voyager::bread.edit-add';

        if (view()->exists("voyager::$slug.edit-add")) {
            $view = "voyager::$slug.edit-add";
        }
  
        $materialsList = Material::pluck('description', 'id');
        $measuresList = Measure::pluck('name', 'id');

        return Voyager::view($view, compact('dataType', 'dataTypeContent', 'isModelTranslatable','materialsList','measuresList'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function show(Request $request, $id)
    {
        return BaseVoyagerController::show($request, $id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function edit(Request $request, $id)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        $relationships = $this->getRelationships($dataType);

        $dataTypeContent = (strlen($dataType->model_name) != 0)
            ? app($dataType->model_name)->with($relationships)->findOrFail($id)
            : DB::table($dataType->name)->where('id', $id)->first(); // If Model doest exist, get data from table name

        foreach ($dataType->editRows as $key => $row) {
            $details = json_decode($row->details);
            $dataType->editRows[$key]['col_width'] = isset($details->width) ? $details->width : 100;
        }

        // If a column has a relationship associated with it, we do not want to show that field
        $this->removeRelationshipField($dataType, 'edit');

        // Check permission
        $this->authorize('edit', $dataTypeContent);

        // Check if BREAD is Translatable
        $isModelTranslatable = is_bread_translatable($dataTypeContent);

        $view = 'voyager::bread.edit-add';

        $materialsList = Material::pluck('description', 'id');
        $measuresList = Measure::pluck('name', 'id');        

        if (view()->exists("voyager::$slug.edit-add")) {
            $view = "voyager::$slug.edit-add";
        }

        return Voyager::view($view, compact('dataType', 'dataTypeContent', 'isModelTranslatable','materialsList','measuresList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function update(Request $request, $id )
    {
        return BaseVoyagerController::update($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function destroy(Request $request, $id)
    {
        return BaseVoyagerController::destroy($request, $id);
    }

}

resources/views/material_measures/create.blade.php
@extends('layouts.app')
@section('htmlheader_title')
{{ __('generic.add') }} {{ __('material_measures.singular') }}
@stop

@section('main-content')

    <h1>{{ __('generic.add') }} {{ __('material_measures.singular') }}</h1>
    <hr/>

    {!! Form::open(['url' => 'material_measures', 'class' => 'form-horizontal']) !!}

        @include('material_measures.fields')

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit( __('material_measures.create'), ['class' => 'btn btn-primary form-control']) !!}
        </div>
        <div class="col-sm-3">
            {{ link_to(PreviousRoute::getNamedRoute('session.index.back'), __('generic.cancel'), ['class' => 'btn btn-primary form-control']) }}
        </div>
    </div>
    {!! Form::close() !!}

    @if ($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif

@endsection

resources/views/material_measures/edit.blade.php
@extends('layouts.app')
@section('htmlheader_title')
{{ __('generic.edit') }} {{ __('material_measures.singular') }}
@stop

@section('main-content')

    <h1>{{ __('generic.edit') }} {{ __('material_measures.singular') }}</h1>
    <hr/>

    {!! Form::model($material_measure, [
        'method' => 'PATCH',
        'url' => ['material_measures', $material_measure->id ],
        'class' => 'form-horizontal'
    ]) !!}

        @include('material_measures.fields')

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit( __('material_measures.update'), ['class' => 'btn btn-primary form-control']) !!}
        </div>
        <div class="col-sm-3">
            {{ link_to(PreviousRoute::getNamedRoute('session.index.back'), __('generic.cancel'), ['class' => 'btn btn-primary form-control']) }}
        </div>        
    </div>
    {!! Form::close() !!}

    @if ($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif

@endsection

resources/views/material_measures/fields.blade.php
<div class="form-group {{ $errors->has('material_id') ? 'has-error' : ''}}">
    {!! Form::label('material_id', __('material_measures.material_id'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::select('material_id', $materialsList, null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('material_id', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('measure_id') ? 'has-error' : ''}}">
    {!! Form::label('measure_id', __('material_measures.measure_id'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::select('measure_id', $measuresList, null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('measure_id', '<p class="help-block">:message</p>') !!}
    </div>
</div>

resources/views/material_measures/index.blade.php
@extends('layouts.app')
@section('htmlheader_title')
{{ __('material_measures.singular') }}
@stop

@section('main-content')

    <h1>{{ __('material_measures.singular') }} 
        {!! Form::open([
                'id'=>'measureAdd',
                'method'=>'GET',
                'url' => route('material_measures.create'),
                'style' => 'display:inline'
            ]) !!}
            {!! Form::hidden('material_id', null, ['id' => 'material_id','class' => 'form-control']) !!}
            {!! Form::submit( __('generic.add_new'), ['class' => 'btn btn-primary pull-right btn-sm','data-remote'=>'false',
                'data-toggle'=>'modal','data-target'=>'#measureModal','data-mode'=>'create']) !!}
        {!! Form::close() !!}        
    </h1>
    <div class="clearfix"></div>
    <div class="box box-default">
        <div class="box-body">
            <table class="table table-bordered table-striped table-hover" id="tblmaterial_measures">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ __('material_measures.material') }}</th>
                        <th>{{ __('material_measures.measure') }}</th>
                        <th>{{ __('material_measures.unit') }}</th>
                        <th>{{ __('material_measures.actions') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="measureModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>   

@endsection

@section('scripts')

<script type="text/javascript">
    var tblmaterial_measures = null;
    $(document).ready(function(){

        $('#measureAdd').on('submit', function(e){
            e.preventDefault();
        });

        $('#measureModal').on("show.bs.modal", function(e){
            var mode = $(e.relatedTarget).data('mode');

            switch(mode) {
            case 'create':
                ajaxLoad( $(e.relatedTarget).closest("form").attr('action'), $('#measureAdd').serializeArray(), $(this).find(".modal-content"), mode );                
                break;
            case 'edit':
                ajaxLoad( $(e.relatedTarget).attr('href'), $('#measureAdd').serializeArray(), $("#measureModal .modal-content"), mode );
                break;
            };

        });

        tblmaterial_measures = $('#tblmaterial_measures').dataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url:  '{{ route('material_measures.list') }}',
                data: {
                    "material_id": $('#material_id').val()
                }
            },
            columns: [
                        { data: 'DT_RowIndex', name: 'DT_RowIndex' },
                        { data: 'material', name: 'material' },
                        { data: 'measure', name: 'measure' },
                        { data: 'unit', name: 'unit' },                        
                        { data: 'action', name: 'action' }
            ],            
            columnDefs: [{
                targets: [0],
                visible: true,
                searchable: false
                },
            ],
            order: [[1, "asc"]],
            language: {!! json_encode(__('datatable')) !!}            
        });

        function ajaxLoad(filename, parameters, container, mode) {
            container = typeof container !== 'undefined' ? container : '#container';
            $('.loading').show();
            $.ajax({
                type: "GET",
                url: filename,
                data: parameters,
                contentType: false,
                success: function (data) {
                    $(container).html(data);
                    $('.loading').hide();
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                }
            });
        }

        $(document).on("click","#add_measure", function(ev)  {

            if(ev.target != this) return false;
            var datastring = $("#frmMaterialMeasure").serializeArray();

            $.ajax({
                type: 'post',
                url: "{{ URL::route('material_measures.store') }}",
                data: datastring,
                error: function (xhr, status, errorThrown) {
                    var alertType = 'error';
                    var alertMessage = xhr.status + ' - ' + errorThrown;
                    var alerter = toastr[alertType];

                    if (xhr.status == '422') {
                        var $errors = xhr.responseJSON;
                        $.each( $errors, function( key, value ) {
                            alertMessage += '<li>' + key + ':' + value + '</li>'; //showing only the first error.
                        });
                        alerter(alertMessage);
                    } else {
                        //Here the status code can be retrieved like;
                        alert(xhr.status + ' - ' + errorThrown );
                    }

                },
                success: function(data) {
                    if ((data.errors)){
                        var alertType = data.status_code;
                        var alertMessage = data.message;
                        var alerter = toastr[alertType];

                        if (alerter) {
                            $.each( data.errors, function( key, value ) {
                                alertMessage += '<li>' + key + ':' + value + '</li>'; //showing only the first error.
                            });

                            alerter(alertMessage);
                        } else {
                            toastr.error("toastr alert-type " + alertType + " is unknown");
                        }

                    }
                    else {
                        tblmaterial_measures.DataTable().api().ajax.reload();
                        toastr.success(" {{ __('material_measures.success_created') }} ");
                        $('#measureModal').modal('hide');
                    }
                },

            });

        });

        $(document).on("click","#edit_measure", function(ev)  {

            if(ev.target != this) return false;
            var cRows = $(ev.currentTarget).data('id');
            
            $.ajax({
                type: 'post',
                url: $("#frmMaterialMeasure").prop('action') ,
                data: $("#frmMaterialMeasure").serializeArray(),
                error: function (xhr, status, errorThrown) {
                    var alertType = 'error';
                    var alertMessage = xhr.status + ' - ' + errorThrown;
                    var alerter = toastr[alertType];

                    if (xhr.status == '422') {
                        var $errors = xhr.responseJSON;
                        $.each( $errors, function( key, value ) {
                            alertMessage += '<li>' + key + ':' + value + '</li>'; //showing only the first error.
                        });
                        alerter(alertMessage);
                    } else {
                        //Here the status code can be retrieved like;
                        alert(xhr.status + ' - ' + errorThrown );
                    }

                },
                success: function(data) {
                    if ((data.errors)){
                        var alertType = data.status_code;
                        var alertMessage = data.message;
                        var alerter = toastr[alertType];

                        if (alerter) {
                            $.each( data.errors, function( key, value ) {
                                alertMessage += '<li>' + key + ':' + value + '</li>'; //showing only the first error.
                            });

                            alerter(alertMessage);
                        } else {
                            toastr.error("toastr alert-type " + alertType + " is unknown");
                        }

                    }
                    else {
                        tblmaterial_measures.DataTable().api().ajax.reload();             
                        toastr.success(" {{ __('material_measures.success_created') }} ");
                        $('#measureModal').modal('hide');
                    }
                },

            });

        });

    });
</script>
@endsection

resources/views/material_measures/list_actions.blade.php
<a href="{{ route('material_measures.edit', ['id'=> $item->id] ) }}" class="btn btn-primary btn-xs edit_measure"
data-toggle='modal' data-remote='false' data-target = '#measureModal' data-mode='edit' >
    {{ __('material_measures.update') }}
</a> 
{!! Form::open([
    'method'=>'DELETE',
    'url' => ['material_measures', $item->id ],
    'style' => 'display:inline'
]) !!}
    {!! Form::submit( __('generic.delete'), ['class' => 'btn btn-danger btn-xs']) !!}
{!! Form::close() !!}

resources/views/material_measures/modal.blade.php
    <form id="frmMaterialMeasure" class="form-horizontal" role="form"
    action="{{ (isset($material_measure->id)) ? route('material_measures.update', $material_measure->id) : route('material_measures.store') }}"
    method="POST" enctype="multipart/form-data" autocomplete="off">
    @if(isset($material_measure->id))
        {{ method_field("PUT") }}
    @endif
    {{ csrf_field() }}
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h5 class="modal-title"><b>{{ (isset($material_measure->id)) ? __('generic.edit') : __('generic.add_new') }} {{ __('material_measures.singular') }} </b></h5>
        </div>
        <div class="modal-body">
        @include('material_measures.fields')
        </div>
        <div class="modal-footer">
        @if(isset($material_measure->id))
        {!! Form::button( __('generic.edit'),['class' => 'btn btn-primary','id'=>'edit_measure','data-id'=>$material_measure->id]) !!}
        @else
        {!! Form::button( __('generic.new'),['class' => 'btn btn-primary','id'=>'add_measure']) !!}
        @endif

        {!! Form::button( __('generic.close'),['class' => 'btn btn-secondary','data-dismiss'=>'modal','id'=>'cancel_measure']) !!}
        </div>
    </form>

resources/views/material_measures/show.blade.php
@extends('layouts.app')
@section('htmlheader_title')
{{ __('material_measures.singular') }}
@stop

@section('main-content')

    <h1>{{ __('material_measures.singular') }}</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>ID.</th> <th>{{ __('material_measures.material') }}</th><th>{{ __('material_measures.measure') }}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> {{ $material_measure->id }} </td>
                    <td> {{ $material_measure->material->description }} </td>
                    <td> {{ $material_measure->measure->name }} </td>
                </tr>
            </tbody>    
        </table>
    </div>

@endsection

resources/views/material_measures/table.blade.php
<div class="table table-responsive">
    <table class="table table-bordered table-striped table-hover" id="tblmaterial_measures">
        <thead>
            <tr>
                <th>ID</th>
                <th>{{ __('material_measures.material') }}</th>
                <th>{{ __('material_measures.measure') }}</th>
                <th>{{ __('material_measures.unit') }}</th>
                <th>{{ __('material_measures.actions') }}</th>
            </tr>
        </thead>
        <tbody>
        @foreach($material_measures as $item)
            <tr data-id="{{ $item->id }}">
                <td><a href="{{ url('material_measures', $item->id) }}">{{ $loop->iteration }}</a></td>
                <td>{{ $item->material->name }}</td>
                <td>{{ $item->measure->name }}</td>
                <td>{{ $item->measure->unit }}</td>
                <td>
                    <?php $data = serialize(['id'=>$item->id,'material_id'=>$item->material_id,'measure_id'=> $item->measure_id]); ?>
                    <a href="{{ route('material_measures.edit', ['id'=> $item->id] ) }}" class="btn btn-primary btn-xs edit_measure"
                    data-toggle='modal' data-remote='false' data-target = '#measureModal' data-mode='edit' >
                        {{ __('material_measures.update') }}
                    </a> 
                    {!! Form::open([
                        'method'=>'DELETE',
                        'url' => ['material_measures', $item->id ],
                        'style' => 'display:inline'
                    ]) !!}
                        {!! Form::submit( __('generic.delete'), ['class' => 'btn btn-danger btn-xs']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>