routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'PageController@about')->name('about');
Route::post('/about',  'PageController@about')->name('about');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => ['web']], function () {
        Route::get('business_partners/identity-document-autocomplete', 'Business_PartnersController@dataIdentityDocument')->name('business_partners.identity-document-autocomplete');
        Route::resource('business_partners', 'Business_PartnersController');

        Route::resource('business_partner_documents', 'Business_Partner_DocumentsController');
        Route::resource('material_providers', 'Material_ProvidersController');
        Route::resource('prices_list', 'Prices_ListController');        

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('stocks/list', 'StocksController@list')->name('stocks.list');
            Route::resource('stocks', 'StocksController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('material_measures/list', 'Material_MeasuresController@list')->name('material_measures.list');
            Route::resource('material_measures', 'Material_MeasuresController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('good_entry/list', 'Good_EntryController@list')->name('good_entry.list');
            Route::get('good_entry/add-provider', 'Good_EntryController@addProvider')->name('good_entry.addProvider');
            Route::get('good_entry/providers-autocomplete', 'Good_EntryController@dataProviders')->name('good_entry.providers-autocomplete');
            Route::get('good_entry/process', 'Good_EntryController@process')->name('good_entry.process');
            Route::resource('good_entry', 'Good_EntryController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('detail_good_entry/materials-autocomplete', 'Detail_Good_EntryController@dataMaterials')->name('detail_good_entry.materials-autocomplete');
            Route::resource('detail_good_entry', 'Detail_Good_EntryController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('delivery_order/list', 'Delivery_OrderController@list')->name('delivery_order.list');
            Route::get('delivery_order/add-customer', 'Delivery_OrderController@addCustomer')->name('delivery_order.addCustomer');
            Route::get('delivery_order/customers-autocomplete', 'Delivery_OrderController@dataCustomers')->name('delivery_order.customers-autocomplete');
            Route::get('delivery_order/process', 'Delivery_OrderController@process')->name('delivery_order.process');
            Route::resource('delivery_order', 'Delivery_OrderController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('detail_delivery_order/materials-autocomplete', 'Detail_Delivery_OrderController@dataMaterials')->name('detail_delivery_order.materials-autocomplete');
            Route::get('detail_delivery_order/material-measures-autocomplete', 'Detail_Delivery_OrderController@dataMeasures')->name('detail_delivery_order.material-measures-autocomplete');
            Route::resource('detail_delivery_order', 'Detail_Delivery_OrderController');
        });

        Route::group(['middleware' => ['caffeinated']], function () {
            Route::get('material/add-measure', 'MaterialController@addMeasure')->name('material.addMeasure');
            Route::resource('material', 'MaterialController');
        });

    });    

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/Good_Entry.php
<?php

namespace App;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Askedio\SoftCascade\Traits\SoftCascadeTrait;
use App\Traits\DatesTranslator;
class Good_Entry extends BaseModel
{
    use SoftDeletes, SoftCascadeTrait, DatesTranslator;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'good_entries';

    /**
     *  Attributes that can search.
     *
     * @var string
     */

    protected $searchableColumns = ['name'];
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['business_partner_id', 'user_id', 'partner_document_id', 'doc_serie', 'doc_num', 'doc_date', 'total', 'status_id'];

    protected $dates = ['doc_date','deleted_at'];

    protected $casts = [
        'total' => 'float(10,2)',
    ];

    public function business_partner() {
        return $this->belongsTo('App\Business_Partner','business_partner_id');
    } 

    public function details_good_entry() {
        return $this->hasMany('App\Detail_Good_Entry');
    }
    
    public function status_description($status_id) {
        return \App\Document_Status::label($status_id);
    }
    
    public function getDocDateLocaleAttribute() {
        return $this->doc_date->isoFormat('L');
    }    
}

app/Http/Controllers/Good_EntryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Helpers\PreviousRoute;
use App\Good_Entry;
use App\Detail_Good_Entry;
use Yajra\Datatables\Datatables;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Session;
use DB;

class Good_EntryController extends Controller
{
    private $business_partner;

    /**
     * Define your validation rules in a property in
     * the controller to reuse the rules.
     */    
    protected $validationRules = [
        'business_partner_id' => 'required',
        'doc_date' => 'required',
        'partner_document_id' => 'required',
        'user_id' => 'required',
        'status_id' => 'required',
        'total'=>'nullable|numeric'
    ];

    public function __construct()
    {   //Assign constant for filter only Customers
        $this->business_partner = config('constants.BusinessPartner_Category.provider');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $good_entry = Good_Entry::all();

        PreviousRoute::setNamedRoute('session.index.back');
        return view('good_entry.index', compact('good_entry'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        // Check permission
        // $this->authorize('add', app('App\Good_Entry'));

        if ($request->exists('id')==true && empty($request->id)==false) {
            $good_entry = Good_Entry::findOrFail($request->id);
        } else {
            $good_entry = array();
        }

        $businessPartnerDocumentList = \App\Business_Partner_Document::select("id","name")
        ->where('partner_category_id','=',$this->business_partner)
        ->pluck('name', 'id');

        $measureList = \App\Measure::select("id","name")->pluck('name', 'id');

        if ($request->exists('id')==true && empty($request->id)==false) {
            $customerList = \App\Business_Partner::select("id","name")->where('id',$good_entry->business_partner_id)->pluck('name', 'id');

            $detailGoodEntry = Detail_Good_Entry::select("detail_good_entries.id","detail_good_entries.good_entry_id",
            "materials.name AS material","measures.name AS measure","detail_good_entries.quantity","detail_good_entries.price",
            "detail_good_entries.subtotal")
            ->join('materials', 'materials.id', '=', 'detail_good_entries.material_id')
            ->join('measures', 'measures.id', '=', 'detail_good_entries.measure_id')
            ->where('detail_good_entries.good_entry_id','=',$request->id)->get();
            
        } else {
            $detailGoodEntry = Detail_Good_Entry::where('good_entry_id',null)->get();
            $customerList = array();
        }

        
        $materialList = array();        
        return view('good_entry.edit-add',compact('good_entry','detailGoodEntry','customerList','businessPartnerDocumentList','materialList','measureList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();
        $inputs['user_id'] = auth()->user()->id;
        $inputs['status_id'] = config('constants.DocumentStatus.open');
 
        $validation = validator()->make($inputs,$this->validationRules);

        if ( $validation->fails() ) {
            $errors = $validation->errors();
            foreach ($errors->all() as $message) {
                toast()->error($message, __('json.validation_errors') );
            }
            //toast()->clear();
            $validation->validate();
        }

        $resource = Good_Entry::create($inputs);

        toast()->success( __('good_entry.error_created'), __('material.message'));

        return redirect()->route('good_entry.create', array('id' => $resource->id) );
       //return redirect('good_entry');
 
    }

    public function process(Request $request)
    {
        
        if($request->has('id')) {

        DB::beginTransaction();
        try {
            $goods_entry = Good_Entry::findOrFail($request->id);
            $detailGoodEntry = Detail_Good_Entry::where('good_entry_id',$request->id)->get();
            
                foreach($detailGoodEntry as $key=>$detail) {

                    $materialProvider = \App\Material_Provider::where([
                        ['material_id', '=', $detail->material_id],
                        ['business_partner_id', '=', $request->business_partner_id],
                        ['measure_id', '=', $detail->measure_id]
                    ])->first();
                
                    if ($materialProvider) {
                        $materialProvider->last_price = $detail->price;
                        //$materialProvider->increment('stock', $detail->quantity);
                        $materialProvider->save();
                    } else {
                        $materialProvider = \App\Material_Provider::firstOrNew(
                            ['material_id' => $detail->material_id,
                            'business_partner_id' => $request->business_partner_id,
                            'measure_id' => $detail->measure_id]
                        );
                        $materialProvider->last_price = $detail->price;
                        $materialProvider->last_purchase = $goods_entry->doc_date;
                        $materialProvider->save();
                    }
                    // Se busca el Almacen General por defecto
                    $storehouse = \App\Storehouse::where('name',__('seeders.warehouse.general.name'))->first();

                    //La logica del ingreso al inventario 
                    $stock = \App\Stock::where([
                        ['material_id', '=', $detail->material_id],
                        ['measure_id', '=', $detail->measure_id]
                    ])->first();
                
                    if ($stock) {
                        $stock->increment('stock', $detail->quantity);
                        $stock->save();
                    } else {
                        $stock = \App\Stock::firstOrNew([
                            'material_id' => $detail->material_id,
                            'measure_id' => $detail->measure_id,
                            'stock' => 0
                        ]);
                        $stock->stock = $detail->quantity;
                        $stock->storehouse_id = $storehouse->id;
                        $stock->save();
                    }
                    //Fin de la logica de ingreso al inventario
                }

                $inputs = $request->all();
                $inputs['user_id'] = auth()->user()->id;
                $inputs['status_id'] = config('constants.DocumentStatus.closed');

                $goods_entry->update($inputs);

                DB::commit();
                $success = true;

            } catch (\Exception $e) {
                $success = false;
                DB::rollback();
            }
                if ($success) {
                    //Si es una peticion ajax
                    if( $request->ajax() ){
                        $indexRoute = PreviousRoute::getNamedRoute('session.index.back','delivery_order.index');
                        return response()->json(['success'=>true,'result'=>$request->input('id'),'url'=> $indexRoute]);
                    } else {
                        toast()->success( __('good_entry.success_processed'), __('material.message'));
                        return redirect()->route('good_entry.index');
                    }                      
                }            
            } else {
                toast()->error( __('good_entry.error_updating'), __('material.message'));
            }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function show($id)
    {
        $good_entry = Good_Entry::findOrFail($id);
        $good_entry->date = Carbon::today();

        $detailGoodEntry = Detail_Good_Entry::select("detail_good_entries.id","detail_good_entries.good_entry_id",
        "materials.name AS material","measures.name AS measure","detail_good_entries.quantity","detail_good_entries.price",
        "detail_good_entries.subtotal")
        ->join('materials', 'materials.id', '=', 'detail_good_entries.material_id')
        ->join('measures', 'measures.id', '=', 'detail_good_entries.measure_id')
        ->where('detail_good_entries.good_entry_id','=',$good_entry->id)->get();

        return view('good_entry.show', compact('good_entry', 'detailGoodEntry'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $good_entry = Good_Entry::findOrFail($id);

        if (empty($good_entry->id)==false) {
            $customerList = \App\Business_Partner::select("id","name")->where('id',$good_entry->business_partner_id)->pluck('name', 'id');

            $detailGoodEntry = Detail_Good_Entry::select("detail_good_entries.id","detail_good_entries.good_entry_id",
            "materials.name AS material","measures.name AS measure","detail_good_entries.quantity","detail_good_entries.price",
            "detail_good_entries.subtotal")
            ->join('materials', 'materials.id', '=', 'detail_good_entries.material_id')
            ->join('measures', 'measures.id', '=', 'detail_good_entries.measure_id')
            ->where('detail_good_entries.good_entry_id','=',$good_entry->id)->get();
            
        } else {
            $detailGoodEntry = Detail_Good_Entry::where('good_entry_id',null)->get();
            $customerList = array();
        }

        $businessPartnerDocumentList = \App\Business_Partner_Document::select("id","name")

resources/views/good_entry/create_business_partner.blade.php
    
    <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
        {!! Form::label('name', __('business_partner.name') , ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('telephone') ? 'has-error' : ''}}">
        {!! Form::label('telephone',  __('business_partner.telephone'), ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('telephone', null, ['class' => 'form-control']) !!}
            {!! $errors->first('telephone', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
        {!! Form::label('email', __('business_partner.email'), ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::email('email', null, ['class' => 'form-control']) !!}
            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('category_id') ? 'has-error' : ''}}">
        {!! Form::label('category_id', __('business_partner.category_id'), ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::select('category_id', $categoriesList, null, ['class' => 'form-control']) !!}
            {!! $errors->first('category_id', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('nit') ? 'has-error' : ''}}">
        {!! Form::label('nit', __('business_partner.nit'), ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('nit', null, ['class' => 'form-control']) !!}
            {!! $errors->first('nit', '<p class="help-block">:message</p>') !!}
        </div>
    </div>

    @if ($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif

resources/views/good_entry/index.blade.php
@extends('layouts.app')
@section('htmlheader_title')
{{ __('good_entry.good_entry') }}
@stop

@section('main-content')

    <h1>{{ __('good_entry.good_entry') }} <a href="{{ url('good_entry/create') }}" class="btn btn-primary pull-right btn-sm">{{ __('generic.add') }} {{ __('good_entry.good_entry') }}</a></h1>
    <div class="table table-responsive">
        <table class="table table-bordered table-striped table-hover" id="tblgoods_entry">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>{{ __('good_entry.business_partner_id') }}</th>
                    <th>{{ __('good_entry.doc_serie') }}</th>
                    <th>{{ __('good_entry.doc_num') }}</th>
                    <th>{{ __('good_entry.doc_date') }}</th>
                    <th>{{ __('good_entry.total') }}</th>
                    <th>{{ __('good_entry.status_id') }}</th>
                    <th>{{ __('good_entry.actions') }}</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){
        $('#tblgoods_entry').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('good_entry.list') !!}',
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                { data: 'business_partner_id', name: 'business_partner_id' },
                { data: 'doc_serie', name: 'doc_serie' },
                { data: 'doc_num', name: 'doc_num' },
                { data: 'doc_date', name: 'doc_date' },
                { data: 'total', name: 'total' },
                { data: 'status_id', name: 'status_id' },
                { data: 'action', name: 'action', orderable: false, searchable: false}
            ],
            order: [[5, "desc"]],             
            language: {!! json_encode(__('datatable')) !!}
        });
    });
</script>
@endsection

resources/views/good_entry/list_actions.blade.php
<a href="{{ route('good_entry.edit', ['id'=> $item->id] ) }}" class="btn btn-primary btn-xs edit_good_entry" >
    {{ __('generic.update') }}
</a> 
{!! Form::open([
    'method'=>'DELETE',
    'url' => ['good_entry', $item->id ],
    'style' => 'display:inline'
]) !!}
    {!! Form::submit( __('generic.delete'), ['class' => 'btn btn-danger btn-xs']) !!}
{!! Form::close() !!}

resources/views/good_entry/show.blade.php
@extends('layouts.app')
@section('htmlheader_title')
{{ __('good_entry.delivery_order') }}
@stop

@section('contentheader_buttons')
    <a id="btn_print" class="btn btn-default" >{{ __('generic.print') }}</a>
    <a href="{{ PreviousRoute::getNamedRoute('session.index.back')}}" class="btn btn-default" >{{ __('good_entry.cancel') }} </a>
@endsection

@section('main-content')
<br>
<section id="formWrapper" class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <i class="fa fa-globe"></i>
            {{ setting('site.title') }}
            <small class="pull-right">{{ $good_entry->date->isoFormat('LL') }}</small>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-10 invoice-col">
          <b>{{ __('good_entry.good_entry') }} #{{ $good_entry->id }}</b><br>
          <br>
          <b>{{ __('good_entry.doc_num') }}:</b> {{ $good_entry->doc_serie }} {{ $good_entry->doc_num }}<br>
          <b>{{ __('good_entry.doc_date') }}:</b> {{ $good_entry->doc_date_locale }} <br>
          <b>{{ __('good_entry.business_partner_id') }}:</b> {{ $good_entry->business_partner_id }}
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>Cantidad</th>
                    <th>Material</th>
                    <th>Medida</th>
                    <th>Precio</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                @foreach($detailGoodEntry as $key=>$item)
                    <tr class="detail_good_entry" data-id="{{ $item->id }}"> 
                        <td>{{ $loop->iteration }}</td>
                        <td data-cell='DTA' data-format="0,0[.]00" >{{ $item->quantity }}</td>
                        <td>{{ $item->material }}</td>
                        <td>{{ $item->measure }}</td>
                        <td data-cell='DTB' data-format="0[.]00" >{{ $item->price }}</td>
                        <td data-cell="{{ 'DTC'.$loop->iteration}}" data-format="0[.]00" >{{ $item->subtotal }}</td>
                    </tr>
                @endforeach
                </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
          <p class="lead">{{ __('good_entry.status_id') }}: {{ $good_entry->status_description($good_entry->status_id) }}</p>

          <div class="table-responsive">
            <table class="table">
              <tr>
                <th>{{ __('good_entry.total') }}:</th>
                <td>{{ $good_entry->total }}</td>
              </tr>
            </table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
        </div>
      </div>
    </section>

@endsection

@section('scripts')
<script src="{{ asset('/plugins/jquery-calx/numeral.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('/plugins/jquery-calx/jquery-calx.min.js') }}" type="text/javascript"></script>

<script type="text/javascript">

    function printElem(divId) {
        var printContents = document.getElementById(divId).innerHTML;
			var originalContents = document.body.innerHTML;
			document.body.innerHTML = printContents;
			window.print();
			document.body.innerHTML = originalContents;
        return true;
    }

    $(document).ready(function() {
        $('#formWrapper').calx({
            readonly : true
        });

        $('section.content').attr('id','page_container');

        $(document).on("click","#btn_print", function(e)  {
            printElem('page_container');
        });

    });
</script>
@stop

resources/views/good_entry/table.blade.php
<div class="table table-responsive">
    <table class="table table-bordered table-striped table-hover" id="tblgood_entry">
        <thead>
            <tr>
                <th>ID</th>
                <th>{{ __('good_entry.business_partner_id') }}</th>
                <th>{{ __('good_entry.doc_serie') }}</th>
                <th>{{ __('good_entry.doc_num') }}</th>
                <th>{{ __('good_entry.doc_date') }}</th>
                <th>{{ __('good_entry.actions') }}</th>
            </tr>
        </thead>
        <tbody>
        @foreach($good_entry as $item)
            <tr>
                <td><a href="{{ url('good_entry', $item->id) }}">{{ $item->id }}</a></td>
                <td>
                    @if ($item->business_partner_id)
                        {{ $item->business_partner->name }}
                    @else
                        {{ $item->business_partner_id }}
                    @endif
                </td>
                <td>{{ $item->doc_serie }}</td>
                <td>{{ $item->doc_num }}</td>
                <td>{{ $item->doc_date->toFormattedDateString() }}</td>
                <td>
                    <a href="{{ url('good_entry/' . $item->id . '/edit') }}" class="btn btn-primary btn-xs">{{__('generic.update')}}</a> 
                    {!! Form::open([
                        'method'=>'DELETE',
                        'url' => ['good_entry', $item->id],
                        'style' => 'display:inline'
                    ]) !!}
                        {!! Form::submit( __('generic.delete') , ['class' => 'btn btn-danger btn-xs']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>